name: Security Checks
on: [push]

jobs:
  test:
    name: OWASP ZAP SCANS
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
         with:
          ref: master
       - name: Building Docker Node-Goat Image
         run: docker-compose build
       - name: Launching the app
         run: docker-compose up --detach

       - name: OWASP ZAP
         uses: zaproxy/action-baseline@v0.9.0
         with:
           # Target URL
           target: "http://localhost:4000"
           fail_action: false
           token: ${{ secrets.GITHUB_TOKEN }}
           issue_title: Security Tests
           docker_name: 'owasp/zap2docker-stable'
           cmd_options: '-a'

       - name: Dastardly Scan Action
  # You may pin to the exact commit or the version.
  # uses: PortSwigger/dastardly-github-action@f72f38f8b4ac8ed59c69854cc77eb9d53e50e78b
         uses: PortSwigger/dastardly-github-action@v1.0.0
         with:
    # The full url (including scheme) of the site to scan
           target-url: http://localhost:4000
    # The filename used for the scan report. This filepath relates to the dastardly container, and will exist in the github workspace (/github/workspace)
           output-filename: dastardly-report.xml # optional, default is dastardly-report.xml
