name: Security 2 Checks
on: [push]

jobs:
  test:
    name: Dastardly SCANS
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
         with:
          ref: master
       - name: Building Docker Node-Goat Image
         run: docker-compose build
       - name: Launching the app
         run: docker-compose up --detach
       - name: Dastardly Scan Action
         uses: PortSwigger/dastardly-github-action@v1.0.0
         with:
           target-url: 'http://localhost:4000'
